<?php
/**
 * ISO Codes
 * 
 * @author Juan Pedro Gonzalez Gutierrez
 * @copyright Copyright (c) 2015 Juan Pedro Gonzalez Gutierrez
 * @license   http://www.gnu.org/licenses/gpl-3.0.en.html GPL v3
 */

namespace IsoCodes\Country\Adapter;

class StaticAdapter implements AdapterInterface
{
    protected $countries = array(
        'AD' => array(
            'alpha_2'           => 'AD',
            'alpha_3'           => 'AND',
            'numeric'           => 20,
            'continent_alpha_2' => 'EU',
            'name'              => 'Andorra',
            'official_name'     => 'Principality of Andorra',
        ),
        'AE' => array(
            'alpha_2'           => 'AE',
            'alpha_3'           => 'ARE',
            'numeric'           => 784,
            'continent_alpha_2' => 'AS',
            'name'              => 'United Arab Emirates',
            'official_name'     => null,
        ),
        'AF' => array(
            'alpha_2'           => 'AF',
            'alpha_3'           => 'AFG',
            'numeric'           => 4,
            'continent_alpha_2' => 'AS',
            'name'              => 'Afghanistan',
            'official_name'     => 'Islamic Republic of Afghanistan',
        ),
        'AG' => array(
            'alpha_2'           => 'AG',
            'alpha_3'           => 'ATG',
            'numeric'           => 28,
            'continent_alpha_2' => 'NA',
            'name'              => 'Antigua and Barbuda',
            'official_name'     => null,
        ),
        'AI' => array(
            'alpha_2'           => 'AI',
            'alpha_3'           => 'AIA',
            'numeric'           => 660,
            'continent_alpha_2' => 'NA',
            'name'              => 'Anguilla',
            'official_name'     => null,
        ),
        'AL' => array(
            'alpha_2'           => 'AL',
            'alpha_3'           => 'ALB',
            'numeric'           => 8,
            'continent_alpha_2' => 'EU',
            'name'              => 'Albania',
            'official_name'     => 'Republic of Albania',
        ),
        'AM' => array(
            'alpha_2'           => 'AM',
            'alpha_3'           => 'ARM',
            'numeric'           => 51,
            'continent_alpha_2' => 'AS',
            'name'              => 'Armenia',
            'official_name'     => 'Republic of Armenia',
        ),
        'AO' => array(
            'alpha_2'           => 'AO',
            'alpha_3'           => 'AGO',
            'numeric'           => 24,
            'continent_alpha_2' => 'AF',
            'name'              => 'Angola',
            'official_name'     => 'Republic of Angola',
        ),
        'AQ' => array(
            'alpha_2'           => 'AQ',
            'alpha_3'           => 'ATA',
            'numeric'           => 10,
            'continent_alpha_2' => 'AN',
            'name'              => 'Antarctica',
            'official_name'     => null,
        ),
        'AR' => array(
            'alpha_2'           => 'AR',
            'alpha_3'           => 'ARG',
            'numeric'           => 32,
            'continent_alpha_2' => 'SA',
            'name'              => 'Argentina',
            'official_name'     => 'Argentine Republic',
        ),
        'AS' => array(
            'alpha_2'           => 'AS',
            'alpha_3'           => 'ASM',
            'numeric'           => 16,
            'continent_alpha_2' => 'OC',
            'name'              => 'American Samoa',
            'official_name'     => null,
        ),
        'AT' => array(
            'alpha_2'           => 'AT',
            'alpha_3'           => 'AUT',
            'numeric'           => 40,
            'continent_alpha_2' => 'EU',
            'name'              => 'Austria',
            'official_name'     => 'Republic of Austria',
        ),
        'AU' => array(
            'alpha_2'           => 'AU',
            'alpha_3'           => 'AUS',
            'numeric'           => 36,
            'continent_alpha_2' => 'OC',
            'name'              => 'Australia',
            'official_name'     => null,
        ),
        'AW' => array(
            'alpha_2'           => 'AW',
            'alpha_3'           => 'ABW',
            'numeric'           => 533,
            'continent_alpha_2' => 'NA',
            'name'              => 'Aruba',
            'official_name'     => null,
        ),
        'AX' => array(
            'alpha_2'           => 'AX',
            'alpha_3'           => 'ALA',
            'numeric'           => 248,
            'continent_alpha_2' => 'EU',
            'name'              => 'Åland Islands',
            'official_name'     => null,
        ),
        'AZ' => array(
            'alpha_2'           => 'AZ',
            'alpha_3'           => 'AZE',
            'numeric'           => 31,
            'continent_alpha_2' => 'AS',
            'name'              => 'Azerbaijan',
            'official_name'     => 'Republic of Azerbaijan',
        ),
        'BA' => array(
            'alpha_2'           => 'BA',
            'alpha_3'           => 'BIH',
            'numeric'           => 70,
            'continent_alpha_2' => 'EU',
            'name'              => 'Bosnia and Herzegovina',
            'official_name'     => 'Republic of Bosnia and Herzegovina',
        ),
        'BB' => array(
            'alpha_2'           => 'BB',
            'alpha_3'           => 'BRB',
            'numeric'           => 52,
            'continent_alpha_2' => 'NA',
            'name'              => 'Barbados',
            'official_name'     => null,
        ),
        'BD' => array(
            'alpha_2'           => 'BD',
            'alpha_3'           => 'BGD',
            'numeric'           => 50,
            'continent_alpha_2' => 'AS',
            'name'              => 'Bangladesh',
            'official_name'     => 'People\'s Republic of Bangladesh',
        ),
        'BE' => array(
            'alpha_2'           => 'BE',
            'alpha_3'           => 'BEL',
            'numeric'           => 56,
            'continent_alpha_2' => 'EU',
            'name'              => 'Belgium',
            'official_name'     => 'Kingdom of Belgium',
        ),
        'BF' => array(
            'alpha_2'           => 'BF',
            'alpha_3'           => 'BFA',
            'numeric'           => 854,
            'continent_alpha_2' => 'AF',
            'name'              => 'Burkina Faso',
            'official_name'     => null,
        ),
        'BG' => array(
            'alpha_2'           => 'BG',
            'alpha_3'           => 'BGR',
            'numeric'           => 100,
            'continent_alpha_2' => 'EU',
            'name'              => 'Bulgaria',
            'official_name'     => 'Republic of Bulgaria',
        ),
        'BH' => array(
            'alpha_2'           => 'BH',
            'alpha_3'           => 'BHR',
            'numeric'           => 48,
            'continent_alpha_2' => 'AS',
            'name'              => 'Bahrain',
            'official_name'     => 'Kingdom of Bahrain',
        ),
        'BI' => array(
            'alpha_2'           => 'BI',
            'alpha_3'           => 'BDI',
            'numeric'           => 108,
            'continent_alpha_2' => 'AF',
            'name'              => 'Burundi',
            'official_name'     => 'Republic of Burundi',
        ),
        'BJ' => array(
            'alpha_2'           => 'BJ',
            'alpha_3'           => 'BEN',
            'numeric'           => 204,
            'continent_alpha_2' => 'AF',
            'name'              => 'Benin',
            'official_name'     => 'Republic of Benin',
        ),
        'BL' => array(
            'alpha_2'           => 'BL',
            'alpha_3'           => 'BLM',
            'numeric'           => 652,
            'continent_alpha_2' => 'NA',
            'name'              => 'Saint Barthélemy',
            'official_name'     => null,
        ),
        'BM' => array(
            'alpha_2'           => 'BM',
            'alpha_3'           => 'BMU',
            'numeric'           => 60,
            'continent_alpha_2' => 'NA',
            'name'              => 'Bermuda',
            'official_name'     => null,
        ),
        'BN' => array(
            'alpha_2'           => 'BN',
            'alpha_3'           => 'BRN',
            'numeric'           => 96,
            'continent_alpha_2' => 'AS',
            'name'              => 'Brunei Darussalam',
            'official_name'     => null,
        ),
        'BO' => array(
            'alpha_2'           => 'BO',
            'alpha_3'           => 'BOL',
            'numeric'           => 68,
            'continent_alpha_2' => 'SA',
            'name'              => 'Bolivia, Plurinational State of',
            'official_name'     => 'Plurinational State of Bolivia',
        ),
        'BR' => array(
            'alpha_2'           => 'BR',
            'alpha_3'           => 'BRA',
            'numeric'           => 76,
            'continent_alpha_2' => 'SA',
            'name'              => 'Brazil',
            'official_name'     => 'Federative Republic of Brazil',
        ),
        'BS' => array(
            'alpha_2'           => 'BS',
            'alpha_3'           => 'BHS',
            'numeric'           => 44,
            'continent_alpha_2' => 'NA',
            'name'              => 'Bahamas',
            'official_name'     => 'Commonwealth of the Bahamas',
        ),
        'BT' => array(
            'alpha_2'           => 'BT',
            'alpha_3'           => 'BTN',
            'numeric'           => 64,
            'continent_alpha_2' => 'AS',
            'name'              => 'Bhutan',
            'official_name'     => 'Kingdom of Bhutan',
        ),
        'BV' => array(
            'alpha_2'           => 'BV',
            'alpha_3'           => 'BVT',
            'numeric'           => 74,
            'continent_alpha_2' => 'AN',
            'name'              => 'Bouvet Island',
            'official_name'     => null,
        ),
        'BW' => array(
            'alpha_2'           => 'BW',
            'alpha_3'           => 'BWA',
            'numeric'           => 72,
            'continent_alpha_2' => 'AF',
            'name'              => 'Botswana',
            'official_name'     => 'Republic of Botswana',
        ),
        'BY' => array(
            'alpha_2'           => 'BY',
            'alpha_3'           => 'BLR',
            'numeric'           => 112,
            'continent_alpha_2' => 'EU',
            'name'              => 'Belarus',
            'official_name'     => 'Republic of Belarus',
        ),
        'BZ' => array(
            'alpha_2'           => 'BZ',
            'alpha_3'           => 'BLZ',
            'numeric'           => 84,
            'continent_alpha_2' => 'NA',
            'name'              => 'Belize',
            'official_name'     => null,
        ),
        'CA' => array(
            'alpha_2'           => 'CA',
            'alpha_3'           => 'CAN',
            'numeric'           => 124,
            'continent_alpha_2' => 'NA',
            'name'              => 'Canada',
            'official_name'     => null,
        ),
        'CC' => array(
            'alpha_2'           => 'CC',
            'alpha_3'           => 'CCK',
            'numeric'           => 166,
            'continent_alpha_2' => 'AS',
            'name'              => 'Cocos (Keeling) Islands',
            'official_name'     => null,
        ),
        'CD' => array(
            'alpha_2'           => 'CD',
            'alpha_3'           => 'COD',
            'numeric'           => 180,
            'continent_alpha_2' => 'AF',
            'name'              => 'Congo, The Democratic Republic of the',
            'official_name'     => null,
        ),
        'CF' => array(
            'alpha_2'           => 'CF',
            'alpha_3'           => 'CAF',
            'numeric'           => 140,
            'continent_alpha_2' => 'AF',
            'name'              => 'Central African Republic',
            'official_name'     => null,
        ),
        'CG' => array(
            'alpha_2'           => 'CG',
            'alpha_3'           => 'COG',
            'numeric'           => 178,
            'continent_alpha_2' => 'AF',
            'name'              => 'Congo',
            'official_name'     => 'Republic of the Congo',
        ),
        'CH' => array(
            'alpha_2'           => 'CH',
            'alpha_3'           => 'CHE',
            'numeric'           => 756,
            'continent_alpha_2' => 'EU',
            'name'              => 'Switzerland',
            'official_name'     => 'Swiss Confederation',
        ),
        'CI' => array(
            'alpha_2'           => 'CI',
            'alpha_3'           => 'CIV',
            'numeric'           => 384,
            'continent_alpha_2' => 'AF',
            'name'              => 'Côte d\'Ivoire',
            'official_name'     => 'Republic of Côte d\'Ivoire',
        ),
        'CK' => array(
            'alpha_2'           => 'CK',
            'alpha_3'           => 'COK',
            'numeric'           => 184,
            'continent_alpha_2' => 'OC',
            'name'              => 'Cook Islands',
            'official_name'     => null,
        ),
        'CL' => array(
            'alpha_2'           => 'CL',
            'alpha_3'           => 'CHL',
            'numeric'           => 152,
            'continent_alpha_2' => 'SA',
            'name'              => 'Chile',
            'official_name'     => 'Republic of Chile',
        ),
        'CM' => array(
            'alpha_2'           => 'CM',
            'alpha_3'           => 'CMR',
            'numeric'           => 120,
            'continent_alpha_2' => 'AF',
            'name'              => 'Cameroon',
            'official_name'     => 'Republic of Cameroon',
        ),
        'CN' => array(
            'alpha_2'           => 'CN',
            'alpha_3'           => 'CHN',
            'numeric'           => 156,
            'continent_alpha_2' => 'AS',
            'name'              => 'China',
            'official_name'     => 'People\'s Republic of China',
        ),
        'CO' => array(
            'alpha_2'           => 'CO',
            'alpha_3'           => 'COL',
            'numeric'           => 170,
            'continent_alpha_2' => 'SA',
            'name'              => 'Colombia',
            'official_name'     => 'Republic of Colombia',
        ),
        'CR' => array(
            'alpha_2'           => 'CR',
            'alpha_3'           => 'CRI',
            'numeric'           => 188,
            'continent_alpha_2' => 'NA',
            'name'              => 'Costa Rica',
            'official_name'     => 'Republic of Costa Rica',
        ),
        'CU' => array(
            'alpha_2'           => 'CU',
            'alpha_3'           => 'CUB',
            'numeric'           => 192,
            'continent_alpha_2' => 'NA',
            'name'              => 'Cuba',
            'official_name'     => 'Republic of Cuba',
        ),
        'CV' => array(
            'alpha_2'           => 'CV',
            'alpha_3'           => 'CPV',
            'numeric'           => 132,
            'continent_alpha_2' => 'AF',
            'name'              => 'Cape Verde',
            'official_name'     => 'Republic of Cape Verde',
        ),
        'CX' => array(
            'alpha_2'           => 'CX',
            'alpha_3'           => 'CXR',
            'numeric'           => 162,
            'continent_alpha_2' => 'AS',
            'name'              => 'Christmas Island',
            'official_name'     => null,
        ),
        'CY' => array(
            'alpha_2'           => 'CY',
            'alpha_3'           => 'CYP',
            'numeric'           => 196,
            'continent_alpha_2' => 'AS',
            'name'              => 'Cyprus',
            'official_name'     => 'Republic of Cyprus',
        ),
        'CZ' => array(
            'alpha_2'           => 'CZ',
            'alpha_3'           => 'CZE',
            'numeric'           => 203,
            'continent_alpha_2' => 'EU',
            'name'              => 'Czech Republic',
            'official_name'     => null,
        ),
        'DE' => array(
            'alpha_2'           => 'DE',
            'alpha_3'           => 'DEU',
            'numeric'           => 276,
            'continent_alpha_2' => 'EU',
            'name'              => 'Germany',
            'official_name'     => 'Federal Republic of Germany',
        ),
        'DJ' => array(
            'alpha_2'           => 'DJ',
            'alpha_3'           => 'DJI',
            'numeric'           => 262,
            'continent_alpha_2' => 'AF',
            'name'              => 'Djibouti',
            'official_name'     => 'Republic of Djibouti',
        ),
        'DK' => array(
            'alpha_2'           => 'DK',
            'alpha_3'           => 'DNK',
            'numeric'           => 208,
            'continent_alpha_2' => 'EU',
            'name'              => 'Denmark',
            'official_name'     => 'Kingdom of Denmark',
        ),
        'DM' => array(
            'alpha_2'           => 'DM',
            'alpha_3'           => 'DMA',
            'numeric'           => 212,
            'continent_alpha_2' => 'NA',
            'name'              => 'Dominica',
            'official_name'     => 'Commonwealth of Dominica',
        ),
        'DO' => array(
            'alpha_2'           => 'DO',
            'alpha_3'           => 'DOM',
            'numeric'           => 214,
            'continent_alpha_2' => 'NA',
            'name'              => 'Dominican Republic',
            'official_name'     => null,
        ),
        'DZ' => array(
            'alpha_2'           => 'DZ',
            'alpha_3'           => 'DZA',
            'numeric'           => 12,
            'continent_alpha_2' => 'AF',
            'name'              => 'Algeria',
            'official_name'     => 'People\'s Democratic Republic of Algeria',
        ),
        'EC' => array(
            'alpha_2'           => 'EC',
            'alpha_3'           => 'ECU',
            'numeric'           => 218,
            'continent_alpha_2' => 'SA',
            'name'              => 'Ecuador',
            'official_name'     => 'Republic of Ecuador',
        ),
        'EE' => array(
            'alpha_2'           => 'EE',
            'alpha_3'           => 'EST',
            'numeric'           => 233,
            'continent_alpha_2' => 'EU',
            'name'              => 'Estonia',
            'official_name'     => 'Republic of Estonia',
        ),
        'EG' => array(
            'alpha_2'           => 'EG',
            'alpha_3'           => 'EGY',
            'numeric'           => 818,
            'continent_alpha_2' => 'AF',
            'name'              => 'Egypt',
            'official_name'     => 'Arab Republic of Egypt',
        ),
        'EH' => array(
            'alpha_2'           => 'EH',
            'alpha_3'           => 'ESH',
            'numeric'           => 732,
            'continent_alpha_2' => 'AF',
            'name'              => 'Western Sahara',
            'official_name'     => null,
        ),
        'ER' => array(
            'alpha_2'           => 'ER',
            'alpha_3'           => 'ERI',
            'numeric'           => 232,
            'continent_alpha_2' => 'AF',
            'name'              => 'Eritrea',
            'official_name'     => 'the State of Eritrea',
        ),
        'ES' => array(
            'alpha_2'           => 'ES',
            'alpha_3'           => 'ESP',
            'numeric'           => 724,
            'continent_alpha_2' => 'EU',
            'name'              => 'Spain',
            'official_name'     => 'Kingdom of Spain',
        ),
        'ET' => array(
            'alpha_2'           => 'ET',
            'alpha_3'           => 'ETH',
            'numeric'           => 231,
            'continent_alpha_2' => 'AF',
            'name'              => 'Ethiopia',
            'official_name'     => 'Federal Democratic Republic of Ethiopia',
        ),
        'FI' => array(
            'alpha_2'           => 'FI',
            'alpha_3'           => 'FIN',
            'numeric'           => 246,
            'continent_alpha_2' => 'EU',
            'name'              => 'Finland',
            'official_name'     => 'Republic of Finland',
        ),
        'FJ' => array(
            'alpha_2'           => 'FJ',
            'alpha_3'           => 'FJI',
            'numeric'           => 242,
            'continent_alpha_2' => 'OC',
            'name'              => 'Fiji',
            'official_name'     => 'Republic of Fiji',
        ),
        'FK' => array(
            'alpha_2'           => 'FK',
            'alpha_3'           => 'FLK',
            'numeric'           => 238,
            'continent_alpha_2' => 'SA',
            'name'              => 'Falkland Islands (Malvinas)',
            'official_name'     => null,
        ),
        'FM' => array(
            'alpha_2'           => 'FM',
            'alpha_3'           => 'FSM',
            'numeric'           => 583,
            'continent_alpha_2' => 'OC',
            'name'              => 'Micronesia, Federated States of',
            'official_name'     => 'Federated States of Micronesia',
        ),
        'FO' => array(
            'alpha_2'           => 'FO',
            'alpha_3'           => 'FRO',
            'numeric'           => 234,
            'continent_alpha_2' => 'EU',
            'name'              => 'Faroe Islands',
            'official_name'     => null,
        ),
        'FR' => array(
            'alpha_2'           => 'FR',
            'alpha_3'           => 'FRA',
            'numeric'           => 250,
            'continent_alpha_2' => 'EU',
            'name'              => 'France',
            'official_name'     => 'French Republic',
        ),
        'GA' => array(
            'alpha_2'           => 'GA',
            'alpha_3'           => 'GAB',
            'numeric'           => 266,
            'continent_alpha_2' => 'AF',
            'name'              => 'Gabon',
            'official_name'     => 'Gabonese Republic',
        ),
        'GB' => array(
            'alpha_2'           => 'GB',
            'alpha_3'           => 'GBR',
            'numeric'           => 826,
            'continent_alpha_2' => 'EU',
            'name'              => 'United Kingdom',
            'official_name'     => 'United Kingdom of Great Britain and Northern Ireland',
        ),
        'GD' => array(
            'alpha_2'           => 'GD',
            'alpha_3'           => 'GRD',
            'numeric'           => 308,
            'continent_alpha_2' => 'NA',
            'name'              => 'Grenada',
            'official_name'     => null,
        ),
        'GE' => array(
            'alpha_2'           => 'GE',
            'alpha_3'           => 'GEO',
            'numeric'           => 268,
            'continent_alpha_2' => 'AS',
            'name'              => 'Georgia',
            'official_name'     => null,
        ),
        'GF' => array(
            'alpha_2'           => 'GF',
            'alpha_3'           => 'GUF',
            'numeric'           => 254,
            'continent_alpha_2' => 'SA',
            'name'              => 'French Guiana',
            'official_name'     => null,
        ),
        'GG' => array(
            'alpha_2'           => 'GG',
            'alpha_3'           => 'GGY',
            'numeric'           => 831,
            'continent_alpha_2' => 'EU',
            'name'              => 'Guernsey',
            'official_name'     => null,
        ),
        'GH' => array(
            'alpha_2'           => 'GH',
            'alpha_3'           => 'GHA',
            'numeric'           => 288,
            'continent_alpha_2' => 'AF',
            'name'              => 'Ghana',
            'official_name'     => 'Republic of Ghana',
        ),
        'GI' => array(
            'alpha_2'           => 'GI',
            'alpha_3'           => 'GIB',
            'numeric'           => 292,
            'continent_alpha_2' => 'EU',
            'name'              => 'Gibraltar',
            'official_name'     => null,
        ),
        'GL' => array(
            'alpha_2'           => 'GL',
            'alpha_3'           => 'GRL',
            'numeric'           => 304,
            'continent_alpha_2' => 'NA',
            'name'              => 'Greenland',
            'official_name'     => null,
        ),
        'GM' => array(
            'alpha_2'           => 'GM',
            'alpha_3'           => 'GMB',
            'numeric'           => 270,
            'continent_alpha_2' => 'AF',
            'name'              => 'Gambia',
            'official_name'     => 'Republic of the Gambia',
        ),
        'GN' => array(
            'alpha_2'           => 'GN',
            'alpha_3'           => 'GIN',
            'numeric'           => 324,
            'continent_alpha_2' => 'AF',
            'name'              => 'Guinea',
            'official_name'     => 'Republic of Guinea',
        ),
        'GP' => array(
            'alpha_2'           => 'GP',
            'alpha_3'           => 'GLP',
            'numeric'           => 312,
            'continent_alpha_2' => 'NA',
            'name'              => 'Guadeloupe',
            'official_name'     => null,
        ),
        'GQ' => array(
            'alpha_2'           => 'GQ',
            'alpha_3'           => 'GNQ',
            'numeric'           => 226,
            'continent_alpha_2' => 'AF',
            'name'              => 'Equatorial Guinea',
            'official_name'     => 'Republic of Equatorial Guinea',
        ),
        'GR' => array(
            'alpha_2'           => 'GR',
            'alpha_3'           => 'GRC',
            'numeric'           => 300,
            'continent_alpha_2' => 'EU',
            'name'              => 'Greece',
            'official_name'     => 'Hellenic Republic',
        ),
        'GS' => array(
            'alpha_2'           => 'GS',
            'alpha_3'           => 'SGS',
            'numeric'           => 239,
            'continent_alpha_2' => 'AN',
            'name'              => 'South Georgia and the South Sandwich Islands',
            'official_name'     => null,
        ),
        'GT' => array(
            'alpha_2'           => 'GT',
            'alpha_3'           => 'GTM',
            'numeric'           => 320,
            'continent_alpha_2' => 'NA',
            'name'              => 'Guatemala',
            'official_name'     => 'Republic of Guatemala',
        ),
        'GU' => array(
            'alpha_2'           => 'GU',
            'alpha_3'           => 'GUM',
            'numeric'           => 316,
            'continent_alpha_2' => 'OC',
            'name'              => 'Guam',
            'official_name'     => null,
        ),
        'GW' => array(
            'alpha_2'           => 'GW',
            'alpha_3'           => 'GNB',
            'numeric'           => 624,
            'continent_alpha_2' => 'AF',
            'name'              => 'Guinea-Bissau',
            'official_name'     => 'Republic of Guinea-Bissau',
        ),
        'GY' => array(
            'alpha_2'           => 'GY',
            'alpha_3'           => 'GUY',
            'numeric'           => 328,
            'continent_alpha_2' => 'SA',
            'name'              => 'Guyana',
            'official_name'     => 'Republic of Guyana',
        ),
        'HK' => array(
            'alpha_2'           => 'HK',
            'alpha_3'           => 'HKG',
            'numeric'           => 344,
            'continent_alpha_2' => 'AS',
            'name'              => 'Hong Kong',
            'official_name'     => 'Hong Kong Special Administrative Region of China',
        ),
        'HM' => array(
            'alpha_2'           => 'HM',
            'alpha_3'           => 'HMD',
            'numeric'           => 334,
            'continent_alpha_2' => 'AN',
            'name'              => 'Heard Island and McDonald Islands',
            'official_name'     => null,
        ),
        'HN' => array(
            'alpha_2'           => 'HN',
            'alpha_3'           => 'HND',
            'numeric'           => 340,
            'continent_alpha_2' => 'NA',
            'name'              => 'Honduras',
            'official_name'     => 'Republic of Honduras',
        ),
        'HR' => array(
            'alpha_2'           => 'HR',
            'alpha_3'           => 'HRV',
            'numeric'           => 191,
            'continent_alpha_2' => 'EU',
            'name'              => 'Croatia',
            'official_name'     => 'Republic of Croatia',
        ),
        'HT' => array(
            'alpha_2'           => 'HT',
            'alpha_3'           => 'HTI',
            'numeric'           => 332,
            'continent_alpha_2' => 'NA',
            'name'              => 'Haiti',
            'official_name'     => 'Republic of Haiti',
        ),
        'HU' => array(
            'alpha_2'           => 'HU',
            'alpha_3'           => 'HUN',
            'numeric'           => 348,
            'continent_alpha_2' => 'EU',
            'name'              => 'Hungary',
            'official_name'     => 'Hungary',
        ),
        'ID' => array(
            'alpha_2'           => 'ID',
            'alpha_3'           => 'IDN',
            'numeric'           => 360,
            'continent_alpha_2' => 'AS',
            'name'              => 'Indonesia',
            'official_name'     => 'Republic of Indonesia',
        ),
        'IE' => array(
            'alpha_2'           => 'IE',
            'alpha_3'           => 'IRL',
            'numeric'           => 372,
            'continent_alpha_2' => 'EU',
            'name'              => 'Ireland',
            'official_name'     => null,
        ),
        'IL' => array(
            'alpha_2'           => 'IL',
            'alpha_3'           => 'ISR',
            'numeric'           => 376,
            'continent_alpha_2' => 'AS',
            'name'              => 'Israel',
            'official_name'     => 'State of Israel',
        ),
        'IM' => array(
            'alpha_2'           => 'IM',
            'alpha_3'           => 'IMN',
            'numeric'           => 833,
            'continent_alpha_2' => 'EU',
            'name'              => 'Isle of Man',
            'official_name'     => null,
        ),
        'IN' => array(
            'alpha_2'           => 'IN',
            'alpha_3'           => 'IND',
            'numeric'           => 356,
            'continent_alpha_2' => 'AS',
            'name'              => 'India',
            'official_name'     => 'Republic of India',
        ),
        'IO' => array(
            'alpha_2'           => 'IO',
            'alpha_3'           => 'IOT',
            'numeric'           => 86,
            'continent_alpha_2' => 'AS',
            'name'              => 'British Indian Ocean Territory',
            'official_name'     => null,
        ),
        'IQ' => array(
            'alpha_2'           => 'IQ',
            'alpha_3'           => 'IRQ',
            'numeric'           => 368,
            'continent_alpha_2' => 'AS',
            'name'              => 'Iraq',
            'official_name'     => 'Republic of Iraq',
        ),
        'IR' => array(
            'alpha_2'           => 'IR',
            'alpha_3'           => 'IRN',
            'numeric'           => 364,
            'continent_alpha_2' => 'AS',
            'name'              => 'Iran, Islamic Republic of',
            'official_name'     => 'Islamic Republic of Iran',
        ),
        'IS' => array(
            'alpha_2'           => 'IS',
            'alpha_3'           => 'ISL',
            'numeric'           => 352,
            'continent_alpha_2' => 'EU',
            'name'              => 'Iceland',
            'official_name'     => 'Republic of Iceland',
        ),
        'IT' => array(
            'alpha_2'           => 'IT',
            'alpha_3'           => 'ITA',
            'numeric'           => 380,
            'continent_alpha_2' => 'EU',
            'name'              => 'Italy',
            'official_name'     => 'Italian Republic',
        ),
        'JE' => array(
            'alpha_2'           => 'JE',
            'alpha_3'           => 'JEY',
            'numeric'           => 832,
            'continent_alpha_2' => 'EU',
            'name'              => 'Jersey',
            'official_name'     => null,
        ),
        'JM' => array(
            'alpha_2'           => 'JM',
            'alpha_3'           => 'JAM',
            'numeric'           => 388,
            'continent_alpha_2' => 'NA',
            'name'              => 'Jamaica',
            'official_name'     => null,
        ),
        'JO' => array(
            'alpha_2'           => 'JO',
            'alpha_3'           => 'JOR',
            'numeric'           => 400,
            'continent_alpha_2' => 'AS',
            'name'              => 'Jordan',
            'official_name'     => 'Hashemite Kingdom of Jordan',
        ),
        'JP' => array(
            'alpha_2'           => 'JP',
            'alpha_3'           => 'JPN',
            'numeric'           => 392,
            'continent_alpha_2' => 'AS',
            'name'              => 'Japan',
            'official_name'     => null,
        ),
        'KE' => array(
            'alpha_2'           => 'KE',
            'alpha_3'           => 'KEN',
            'numeric'           => 404,
            'continent_alpha_2' => 'AF',
            'name'              => 'Kenya',
            'official_name'     => 'Republic of Kenya',
        ),
        'KG' => array(
            'alpha_2'           => 'KG',
            'alpha_3'           => 'KGZ',
            'numeric'           => 417,
            'continent_alpha_2' => 'AS',
            'name'              => 'Kyrgyzstan',
            'official_name'     => 'Kyrgyz Republic',
        ),
        'KH' => array(
            'alpha_2'           => 'KH',
            'alpha_3'           => 'KHM',
            'numeric'           => 116,
            'continent_alpha_2' => 'AS',
            'name'              => 'Cambodia',
            'official_name'     => 'Kingdom of Cambodia',
        ),
        'KI' => array(
            'alpha_2'           => 'KI',
            'alpha_3'           => 'KIR',
            'numeric'           => 296,
            'continent_alpha_2' => 'OC',
            'name'              => 'Kiribati',
            'official_name'     => 'Republic of Kiribati',
        ),
        'KM' => array(
            'alpha_2'           => 'KM',
            'alpha_3'           => 'COM',
            'numeric'           => 174,
            'continent_alpha_2' => 'AF',
            'name'              => 'Comoros',
            'official_name'     => 'Union of the Comoros',
        ),
        'KN' => array(
            'alpha_2'           => 'KN',
            'alpha_3'           => 'KNA',
            'numeric'           => 659,
            'continent_alpha_2' => 'NA',
            'name'              => 'Saint Kitts and Nevis',
            'official_name'     => null,
        ),
        'KP' => array(
            'alpha_2'           => 'KP',
            'alpha_3'           => 'PRK',
            'numeric'           => 408,
            'continent_alpha_2' => 'AS',
            'name'              => 'Korea, Democratic People\'s Republic of',
            'official_name'     => 'Democratic People\'s Republic of Korea',
        ),
        'KR' => array(
            'alpha_2'           => 'KR',
            'alpha_3'           => 'KOR',
            'numeric'           => 410,
            'continent_alpha_2' => 'AS',
            'name'              => 'Korea, Republic of',
            'official_name'     => null,
        ),
        'KW' => array(
            'alpha_2'           => 'KW',
            'alpha_3'           => 'KWT',
            'numeric'           => 414,
            'continent_alpha_2' => 'AS',
            'name'              => 'Kuwait',
            'official_name'     => 'State of Kuwait',
        ),
        'KY' => array(
            'alpha_2'           => 'KY',
            'alpha_3'           => 'CYM',
            'numeric'           => 136,
            'continent_alpha_2' => 'NA',
            'name'              => 'Cayman Islands',
            'official_name'     => null,
        ),
        'KZ' => array(
            'alpha_2'           => 'KZ',
            'alpha_3'           => 'KAZ',
            'numeric'           => 398,
            'continent_alpha_2' => 'AS',
            'name'              => 'Kazakhstan',
            'official_name'     => 'Republic of Kazakhstan',
        ),
        'LA' => array(
            'alpha_2'           => 'LA',
            'alpha_3'           => 'LAO',
            'numeric'           => 418,
            'continent_alpha_2' => 'AS',
            'name'              => 'Lao People\'s Democratic Republic',
            'official_name'     => null,
        ),
        'LB' => array(
            'alpha_2'           => 'LB',
            'alpha_3'           => 'LBN',
            'numeric'           => 422,
            'continent_alpha_2' => 'AS',
            'name'              => 'Lebanon',
            'official_name'     => 'Lebanese Republic',
        ),
        'LC' => array(
            'alpha_2'           => 'LC',
            'alpha_3'           => 'LCA',
            'numeric'           => 662,
            'continent_alpha_2' => 'NA',
            'name'              => 'Saint Lucia',
            'official_name'     => null,
        ),
        'LI' => array(
            'alpha_2'           => 'LI',
            'alpha_3'           => 'LIE',
            'numeric'           => 438,
            'continent_alpha_2' => 'EU',
            'name'              => 'Liechtenstein',
            'official_name'     => 'Principality of Liechtenstein',
        ),
        'LK' => array(
            'alpha_2'           => 'LK',
            'alpha_3'           => 'LKA',
            'numeric'           => 144,
            'continent_alpha_2' => 'AS',
            'name'              => 'Sri Lanka',
            'official_name'     => 'Democratic Socialist Republic of Sri Lanka',
        ),
        'LR' => array(
            'alpha_2'           => 'LR',
            'alpha_3'           => 'LBR',
            'numeric'           => 430,
            'continent_alpha_2' => 'AF',
            'name'              => 'Liberia',
            'official_name'     => 'Republic of Liberia',
        ),
        'LS' => array(
            'alpha_2'           => 'LS',
            'alpha_3'           => 'LSO',
            'numeric'           => 426,
            'continent_alpha_2' => 'AF',
            'name'              => 'Lesotho',
            'official_name'     => 'Kingdom of Lesotho',
        ),
        'LT' => array(
            'alpha_2'           => 'LT',
            'alpha_3'           => 'LTU',
            'numeric'           => 440,
            'continent_alpha_2' => 'EU',
            'name'              => 'Lithuania',
            'official_name'     => 'Republic of Lithuania',
        ),
        'LU' => array(
            'alpha_2'           => 'LU',
            'alpha_3'           => 'LUX',
            'numeric'           => 442,
            'continent_alpha_2' => 'EU',
            'name'              => 'Luxembourg',
            'official_name'     => 'Grand Duchy of Luxembourg',
        ),
        'LV' => array(
            'alpha_2'           => 'LV',
            'alpha_3'           => 'LVA',
            'numeric'           => 428,
            'continent_alpha_2' => 'EU',
            'name'              => 'Latvia',
            'official_name'     => 'Republic of Latvia',
        ),
        'LY' => array(
            'alpha_2'           => 'LY',
            'alpha_3'           => 'LBY',
            'numeric'           => 434,
            'continent_alpha_2' => 'AF',
            'name'              => 'Libya',
            'official_name'     => 'Libya',
        ),
        'MA' => array(
            'alpha_2'           => 'MA',
            'alpha_3'           => 'MAR',
            'numeric'           => 504,
            'continent_alpha_2' => 'AF',
            'name'              => 'Morocco',
            'official_name'     => 'Kingdom of Morocco',
        ),
        'MC' => array(
            'alpha_2'           => 'MC',
            'alpha_3'           => 'MCO',
            'numeric'           => 492,
            'continent_alpha_2' => 'EU',
            'name'              => 'Monaco',
            'official_name'     => 'Principality of Monaco',
        ),
        'MD' => array(
            'alpha_2'           => 'MD',
            'alpha_3'           => 'MDA',
            'numeric'           => 498,
            'continent_alpha_2' => 'EU',
            'name'              => 'Moldova, Republic of',
            'official_name'     => 'Republic of Moldova',
        ),
        'ME' => array(
            'alpha_2'           => 'ME',
            'alpha_3'           => 'MNE',
            'numeric'           => 499,
            'continent_alpha_2' => 'EU',
            'name'              => 'Montenegro',
            'official_name'     => 'Montenegro',
        ),
        'MF' => array(
            'alpha_2'           => 'MF',
            'alpha_3'           => 'MAF',
            'numeric'           => 663,
            'continent_alpha_2' => 'NA',
            'name'              => 'Saint Martin (French part)',
            'official_name'     => null,
        ),
        'MG' => array(
            'alpha_2'           => 'MG',
            'alpha_3'           => 'MDG',
            'numeric'           => 450,
            'continent_alpha_2' => 'AF',
            'name'              => 'Madagascar',
            'official_name'     => 'Republic of Madagascar',
        ),
        'MH' => array(
            'alpha_2'           => 'MH',
            'alpha_3'           => 'MHL',
            'numeric'           => 584,
            'continent_alpha_2' => 'OC',
            'name'              => 'Marshall Islands',
            'official_name'     => 'Republic of the Marshall Islands',
        ),
        'MK' => array(
            'alpha_2'           => 'MK',
            'alpha_3'           => 'MKD',
            'numeric'           => 807,
            'continent_alpha_2' => 'EU',
            'name'              => 'Macedonia, Republic of',
            'official_name'     => 'The Former Yugoslav Republic of Macedonia',
        ),
        'ML' => array(
            'alpha_2'           => 'ML',
            'alpha_3'           => 'MLI',
            'numeric'           => 466,
            'continent_alpha_2' => 'AF',
            'name'              => 'Mali',
            'official_name'     => 'Republic of Mali',
        ),
        'MM' => array(
            'alpha_2'           => 'MM',
            'alpha_3'           => 'MMR',
            'numeric'           => 104,
            'continent_alpha_2' => 'AS',
            'name'              => 'Myanmar',
            'official_name'     => 'Republic of Myanmar',
        ),
        'MN' => array(
            'alpha_2'           => 'MN',
            'alpha_3'           => 'MNG',
            'numeric'           => 496,
            'continent_alpha_2' => 'AS',
            'name'              => 'Mongolia',
            'official_name'     => null,
        ),
        'MO' => array(
            'alpha_2'           => 'MO',
            'alpha_3'           => 'MAC',
            'numeric'           => 446,
            'continent_alpha_2' => 'AS',
            'name'              => 'Macao',
            'official_name'     => 'Macao Special Administrative Region of China',
        ),
        'MP' => array(
            'alpha_2'           => 'MP',
            'alpha_3'           => 'MNP',
            'numeric'           => 580,
            'continent_alpha_2' => 'OC',
            'name'              => 'Northern Mariana Islands',
            'official_name'     => 'Commonwealth of the Northern Mariana Islands',
        ),
        'MQ' => array(
            'alpha_2'           => 'MQ',
            'alpha_3'           => 'MTQ',
            'numeric'           => 474,
            'continent_alpha_2' => 'NA',
            'name'              => 'Martinique',
            'official_name'     => null,
        ),
        'MR' => array(
            'alpha_2'           => 'MR',
            'alpha_3'           => 'MRT',
            'numeric'           => 478,
            'continent_alpha_2' => 'AF',
            'name'              => 'Mauritania',
            'official_name'     => 'Islamic Republic of Mauritania',
        ),
        'MS' => array(
            'alpha_2'           => 'MS',
            'alpha_3'           => 'MSR',
            'numeric'           => 500,
            'continent_alpha_2' => 'NA',
            'name'              => 'Montserrat',
            'official_name'     => null,
        ),
        'MT' => array(
            'alpha_2'           => 'MT',
            'alpha_3'           => 'MLT',
            'numeric'           => 470,
            'continent_alpha_2' => 'EU',
            'name'              => 'Malta',
            'official_name'     => 'Republic of Malta',
        ),
        'MU' => array(
            'alpha_2'           => 'MU',
            'alpha_3'           => 'MUS',
            'numeric'           => 480,
            'continent_alpha_2' => 'AF',
            'name'              => 'Mauritius',
            'official_name'     => 'Republic of Mauritius',
        ),
        'MV' => array(
            'alpha_2'           => 'MV',
            'alpha_3'           => 'MDV',
            'numeric'           => 462,
            'continent_alpha_2' => 'AS',
            'name'              => 'Maldives',
            'official_name'     => 'Republic of Maldives',
        ),
        'MW' => array(
            'alpha_2'           => 'MW',
            'alpha_3'           => 'MWI',
            'numeric'           => 454,
            'continent_alpha_2' => 'AF',
            'name'              => 'Malawi',
            'official_name'     => 'Republic of Malawi',
        ),
        'MX' => array(
            'alpha_2'           => 'MX',
            'alpha_3'           => 'MEX',
            'numeric'           => 484,
            'continent_alpha_2' => 'NA',
            'name'              => 'Mexico',
            'official_name'     => 'United Mexican States',
        ),
        'MY' => array(
            'alpha_2'           => 'MY',
            'alpha_3'           => 'MYS',
            'numeric'           => 458,
            'continent_alpha_2' => 'AS',
            'name'              => 'Malaysia',
            'official_name'     => null,
        ),
        'MZ' => array(
            'alpha_2'           => 'MZ',
            'alpha_3'           => 'MOZ',
            'numeric'           => 508,
            'continent_alpha_2' => 'AF',
            'name'              => 'Mozambique',
            'official_name'     => 'Republic of Mozambique',
        ),
        'NA' => array(
            'alpha_2'           => 'NA',
            'alpha_3'           => 'NAM',
            'numeric'           => 516,
            'continent_alpha_2' => 'AF',
            'name'              => 'Namibia',
            'official_name'     => 'Republic of Namibia',
        ),
        'NC' => array(
            'alpha_2'           => 'NC',
            'alpha_3'           => 'NCL',
            'numeric'           => 540,
            'continent_alpha_2' => 'OC',
            'name'              => 'New Caledonia',
            'official_name'     => null,
        ),
        'NE' => array(
            'alpha_2'           => 'NE',
            'alpha_3'           => 'NER',
            'numeric'           => 562,
            'continent_alpha_2' => 'AF',
            'name'              => 'Niger',
            'official_name'     => 'Republic of the Niger',
        ),
        'NF' => array(
            'alpha_2'           => 'NF',
            'alpha_3'           => 'NFK',
            'numeric'           => 574,
            'continent_alpha_2' => 'OC',
            'name'              => 'Norfolk Island',
            'official_name'     => null,
        ),
        'NG' => array(
            'alpha_2'           => 'NG',
            'alpha_3'           => 'NGA',
            'numeric'           => 566,
            'continent_alpha_2' => 'AF',
            'name'              => 'Nigeria',
            'official_name'     => 'Federal Republic of Nigeria',
        ),
        'NI' => array(
            'alpha_2'           => 'NI',
            'alpha_3'           => 'NIC',
            'numeric'           => 558,
            'continent_alpha_2' => 'NA',
            'name'              => 'Nicaragua',
            'official_name'     => 'Republic of Nicaragua',
        ),
        'NL' => array(
            'alpha_2'           => 'NL',
            'alpha_3'           => 'NLD',
            'numeric'           => 528,
            'continent_alpha_2' => 'EU',
            'name'              => 'Netherlands',
            'official_name'     => 'Kingdom of the Netherlands',
        ),
        'NO' => array(
            'alpha_2'           => 'NO',
            'alpha_3'           => 'NOR',
            'numeric'           => 578,
            'continent_alpha_2' => 'EU',
            'name'              => 'Norway',
            'official_name'     => 'Kingdom of Norway',
        ),
        'NP' => array(
            'alpha_2'           => 'NP',
            'alpha_3'           => 'NPL',
            'numeric'           => 524,
            'continent_alpha_2' => 'AS',
            'name'              => 'Nepal',
            'official_name'     => 'Federal Democratic Republic of Nepal',
        ),
        'NR' => array(
            'alpha_2'           => 'NR',
            'alpha_3'           => 'NRU',
            'numeric'           => 520,
            'continent_alpha_2' => 'OC',
            'name'              => 'Nauru',
            'official_name'     => 'Republic of Nauru',
        ),
        'NU' => array(
            'alpha_2'           => 'NU',
            'alpha_3'           => 'NIU',
            'numeric'           => 570,
            'continent_alpha_2' => 'OC',
            'name'              => 'Niue',
            'official_name'     => 'Niue',
        ),
        'NZ' => array(
            'alpha_2'           => 'NZ',
            'alpha_3'           => 'NZL',
            'numeric'           => 554,
            'continent_alpha_2' => 'OC',
            'name'              => 'New Zealand',
            'official_name'     => null,
        ),
        'OM' => array(
            'alpha_2'           => 'OM',
            'alpha_3'           => 'OMN',
            'numeric'           => 512,
            'continent_alpha_2' => 'AS',
            'name'              => 'Oman',
            'official_name'     => 'Sultanate of Oman',
        ),
        'PA' => array(
            'alpha_2'           => 'PA',
            'alpha_3'           => 'PAN',
            'numeric'           => 591,
            'continent_alpha_2' => 'NA',
            'name'              => 'Panama',
            'official_name'     => 'Republic of Panama',
        ),
        'PE' => array(
            'alpha_2'           => 'PE',
            'alpha_3'           => 'PER',
            'numeric'           => 604,
            'continent_alpha_2' => 'SA',
            'name'              => 'Peru',
            'official_name'     => 'Republic of Peru',
        ),
        'PF' => array(
            'alpha_2'           => 'PF',
            'alpha_3'           => 'PYF',
            'numeric'           => 258,
            'continent_alpha_2' => 'OC',
            'name'              => 'French Polynesia',
            'official_name'     => null,
        ),
        'PG' => array(
            'alpha_2'           => 'PG',
            'alpha_3'           => 'PNG',
            'numeric'           => 598,
            'continent_alpha_2' => 'OC',
            'name'              => 'Papua New Guinea',
            'official_name'     => 'Independent State of Papua New Guinea',
        ),
        'PH' => array(
            'alpha_2'           => 'PH',
            'alpha_3'           => 'PHL',
            'numeric'           => 608,
            'continent_alpha_2' => 'AS',
            'name'              => 'Philippines',
            'official_name'     => 'Republic of the Philippines',
        ),
        'PK' => array(
            'alpha_2'           => 'PK',
            'alpha_3'           => 'PAK',
            'numeric'           => 586,
            'continent_alpha_2' => 'AS',
            'name'              => 'Pakistan',
            'official_name'     => 'Islamic Republic of Pakistan',
        ),
        'PL' => array(
            'alpha_2'           => 'PL',
            'alpha_3'           => 'POL',
            'numeric'           => 616,
            'continent_alpha_2' => 'EU',
            'name'              => 'Poland',
            'official_name'     => 'Republic of Poland',
        ),
        'PM' => array(
            'alpha_2'           => 'PM',
            'alpha_3'           => 'SPM',
            'numeric'           => 666,
            'continent_alpha_2' => 'NA',
            'name'              => 'Saint Pierre and Miquelon',
            'official_name'     => null,
        ),
        'PN' => array(
            'alpha_2'           => 'PN',
            'alpha_3'           => 'PCN',
            'numeric'           => 612,
            'continent_alpha_2' => 'OC',
            'name'              => 'Pitcairn',
            'official_name'     => null,
        ),
        'PR' => array(
            'alpha_2'           => 'PR',
            'alpha_3'           => 'PRI',
            'numeric'           => 630,
            'continent_alpha_2' => 'NA',
            'name'              => 'Puerto Rico',
            'official_name'     => null,
        ),
        'PS' => array(
            'alpha_2'           => 'PS',
            'alpha_3'           => 'PSE',
            'numeric'           => 275,
            'continent_alpha_2' => 'AS',
            'name'              => 'Palestine, State of',
            'official_name'     => 'the State of Palestine',
        ),
        'PT' => array(
            'alpha_2'           => 'PT',
            'alpha_3'           => 'PRT',
            'numeric'           => 620,
            'continent_alpha_2' => 'EU',
            'name'              => 'Portugal',
            'official_name'     => 'Portuguese Republic',
        ),
        'PW' => array(
            'alpha_2'           => 'PW',
            'alpha_3'           => 'PLW',
            'numeric'           => 585,
            'continent_alpha_2' => 'OC',
            'name'              => 'Palau',
            'official_name'     => 'Republic of Palau',
        ),
        'PY' => array(
            'alpha_2'           => 'PY',
            'alpha_3'           => 'PRY',
            'numeric'           => 600,
            'continent_alpha_2' => 'SA',
            'name'              => 'Paraguay',
            'official_name'     => 'Republic of Paraguay',
        ),
        'QA' => array(
            'alpha_2'           => 'QA',
            'alpha_3'           => 'QAT',
            'numeric'           => 634,
            'continent_alpha_2' => 'AS',
            'name'              => 'Qatar',
            'official_name'     => 'State of Qatar',
        ),
        'RE' => array(
            'alpha_2'           => 'RE',
            'alpha_3'           => 'REU',
            'numeric'           => 638,
            'continent_alpha_2' => 'AF',
            'name'              => 'Réunion',
            'official_name'     => null,
        ),
        'RO' => array(
            'alpha_2'           => 'RO',
            'alpha_3'           => 'ROU',
            'numeric'           => 642,
            'continent_alpha_2' => 'EU',
            'name'              => 'Romania',
            'official_name'     => null,
        ),
        'RS' => array(
            'alpha_2'           => 'RS',
            'alpha_3'           => 'SRB',
            'numeric'           => 688,
            'continent_alpha_2' => 'EU',
            'name'              => 'Serbia',
            'official_name'     => 'Republic of Serbia',
        ),
        'RU' => array(
            'alpha_2'           => 'RU',
            'alpha_3'           => 'RUS',
            'numeric'           => 643,
            'continent_alpha_2' => 'EU',
            'name'              => 'Russian Federation',
            'official_name'     => null,
        ),
        'RW' => array(
            'alpha_2'           => 'RW',
            'alpha_3'           => 'RWA',
            'numeric'           => 646,
            'continent_alpha_2' => 'AF',
            'name'              => 'Rwanda',
            'official_name'     => 'Rwandese Republic',
        ),
        'SA' => array(
            'alpha_2'           => 'SA',
            'alpha_3'           => 'SAU',
            'numeric'           => 682,
            'continent_alpha_2' => 'AS',
            'name'              => 'Saudi Arabia',
            'official_name'     => 'Kingdom of Saudi Arabia',
        ),
        'SB' => array(
            'alpha_2'           => 'SB',
            'alpha_3'           => 'SLB',
            'numeric'           => 90,
            'continent_alpha_2' => 'OC',
            'name'              => 'Solomon Islands',
            'official_name'     => null,
        ),
        'SC' => array(
            'alpha_2'           => 'SC',
            'alpha_3'           => 'SYC',
            'numeric'           => 690,
            'continent_alpha_2' => 'AF',
            'name'              => 'Seychelles',
            'official_name'     => 'Republic of Seychelles',
        ),
        'SD' => array(
            'alpha_2'           => 'SD',
            'alpha_3'           => 'SDN',
            'numeric'           => 729,
            'continent_alpha_2' => 'AF',
            'name'              => 'Sudan',
            'official_name'     => 'Republic of the Sudan',
        ),
        'SE' => array(
            'alpha_2'           => 'SE',
            'alpha_3'           => 'SWE',
            'numeric'           => 752,
            'continent_alpha_2' => 'EU',
            'name'              => 'Sweden',
            'official_name'     => 'Kingdom of Sweden',
        ),
        'SG' => array(
            'alpha_2'           => 'SG',
            'alpha_3'           => 'SGP',
            'numeric'           => 702,
            'continent_alpha_2' => 'AS',
            'name'              => 'Singapore',
            'official_name'     => 'Republic of Singapore',
        ),
        'SH' => array(
            'alpha_2'           => 'SH',
            'alpha_3'           => 'SHN',
            'numeric'           => 654,
            'continent_alpha_2' => 'AF',
            'name'              => 'Saint Helena, Ascension and Tristan da Cunha',
            'official_name'     => null,
        ),
        'SI' => array(
            'alpha_2'           => 'SI',
            'alpha_3'           => 'SVN',
            'numeric'           => 705,
            'continent_alpha_2' => 'EU',
            'name'              => 'Slovenia',
            'official_name'     => 'Republic of Slovenia',
        ),
        'SJ' => array(
            'alpha_2'           => 'SJ',
            'alpha_3'           => 'SJM',
            'numeric'           => 744,
            'continent_alpha_2' => 'EU',
            'name'              => 'Svalbard and Jan Mayen',
            'official_name'     => null,
        ),
        'SK' => array(
            'alpha_2'           => 'SK',
            'alpha_3'           => 'SVK',
            'numeric'           => 703,
            'continent_alpha_2' => 'EU',
            'name'              => 'Slovakia',
            'official_name'     => 'Slovak Republic',
        ),
        'SL' => array(
            'alpha_2'           => 'SL',
            'alpha_3'           => 'SLE',
            'numeric'           => 694,
            'continent_alpha_2' => 'AF',
            'name'              => 'Sierra Leone',
            'official_name'     => 'Republic of Sierra Leone',
        ),
        'SM' => array(
            'alpha_2'           => 'SM',
            'alpha_3'           => 'SMR',
            'numeric'           => 674,
            'continent_alpha_2' => 'EU',
            'name'              => 'San Marino',
            'official_name'     => 'Republic of San Marino',
        ),
        'SN' => array(
            'alpha_2'           => 'SN',
            'alpha_3'           => 'SEN',
            'numeric'           => 686,
            'continent_alpha_2' => 'AF',
            'name'              => 'Senegal',
            'official_name'     => 'Republic of Senegal',
        ),
        'SO' => array(
            'alpha_2'           => 'SO',
            'alpha_3'           => 'SOM',
            'numeric'           => 706,
            'continent_alpha_2' => 'AF',
            'name'              => 'Somalia',
            'official_name'     => 'Federal Republic of Somalia',
        ),
        'SR' => array(
            'alpha_2'           => 'SR',
            'alpha_3'           => 'SUR',
            'numeric'           => 740,
            'continent_alpha_2' => 'SA',
            'name'              => 'Suriname',
            'official_name'     => 'Republic of Suriname',
        ),
        'ST' => array(
            'alpha_2'           => 'ST',
            'alpha_3'           => 'STP',
            'numeric'           => 678,
            'continent_alpha_2' => 'AF',
            'name'              => 'Sao Tome and Principe',
            'official_name'     => 'Democratic Republic of Sao Tome and Principe',
        ),
        'SV' => array(
            'alpha_2'           => 'SV',
            'alpha_3'           => 'SLV',
            'numeric'           => 222,
            'continent_alpha_2' => 'NA',
            'name'              => 'El Salvador',
            'official_name'     => 'Republic of El Salvador',
        ),
        'SY' => array(
            'alpha_2'           => 'SY',
            'alpha_3'           => 'SYR',
            'numeric'           => 760,
            'continent_alpha_2' => 'AS',
            'name'              => 'Syrian Arab Republic',
            'official_name'     => null,
        ),
        'SZ' => array(
            'alpha_2'           => 'SZ',
            'alpha_3'           => 'SWZ',
            'numeric'           => 748,
            'continent_alpha_2' => 'AF',
            'name'              => 'Swaziland',
            'official_name'     => 'Kingdom of Swaziland',
        ),
        'TC' => array(
            'alpha_2'           => 'TC',
            'alpha_3'           => 'TCA',
            'numeric'           => 796,
            'continent_alpha_2' => 'NA',
            'name'              => 'Turks and Caicos Islands',
            'official_name'     => null,
        ),
        'TD' => array(
            'alpha_2'           => 'TD',
            'alpha_3'           => 'TCD',
            'numeric'           => 148,
            'continent_alpha_2' => 'AF',
            'name'              => 'Chad',
            'official_name'     => 'Republic of Chad',
        ),
        'TF' => array(
            'alpha_2'           => 'TF',
            'alpha_3'           => 'ATF',
            'numeric'           => 260,
            'continent_alpha_2' => 'AN',
            'name'              => 'French Southern Territories',
            'official_name'     => null,
        ),
        'TG' => array(
            'alpha_2'           => 'TG',
            'alpha_3'           => 'TGO',
            'numeric'           => 768,
            'continent_alpha_2' => 'AF',
            'name'              => 'Togo',
            'official_name'     => 'Togolese Republic',
        ),
        'TH' => array(
            'alpha_2'           => 'TH',
            'alpha_3'           => 'THA',
            'numeric'           => 764,
            'continent_alpha_2' => 'AS',
            'name'              => 'Thailand',
            'official_name'     => 'Kingdom of Thailand',
        ),
        'TJ' => array(
            'alpha_2'           => 'TJ',
            'alpha_3'           => 'TJK',
            'numeric'           => 762,
            'continent_alpha_2' => 'AS',
            'name'              => 'Tajikistan',
            'official_name'     => 'Republic of Tajikistan',
        ),
        'TK' => array(
            'alpha_2'           => 'TK',
            'alpha_3'           => 'TKL',
            'numeric'           => 772,
            'continent_alpha_2' => 'OC',
            'name'              => 'Tokelau',
            'official_name'     => null,
        ),
        'TL' => array(
            'alpha_2'           => 'TL',
            'alpha_3'           => 'TLS',
            'numeric'           => 626,
            'continent_alpha_2' => 'AS',
            'name'              => 'Timor-Leste',
            'official_name'     => 'Democratic Republic of Timor-Leste',
        ),
        'TM' => array(
            'alpha_2'           => 'TM',
            'alpha_3'           => 'TKM',
            'numeric'           => 795,
            'continent_alpha_2' => 'AS',
            'name'              => 'Turkmenistan',
            'official_name'     => null,
        ),
        'TN' => array(
            'alpha_2'           => 'TN',
            'alpha_3'           => 'TUN',
            'numeric'           => 788,
            'continent_alpha_2' => 'AF',
            'name'              => 'Tunisia',
            'official_name'     => 'Republic of Tunisia',
        ),
        'TO' => array(
            'alpha_2'           => 'TO',
            'alpha_3'           => 'TON',
            'numeric'           => 776,
            'continent_alpha_2' => 'OC',
            'name'              => 'Tonga',
            'official_name'     => 'Kingdom of Tonga',
        ),
        'TR' => array(
            'alpha_2'           => 'TR',
            'alpha_3'           => 'TUR',
            'numeric'           => 792,
            'continent_alpha_2' => 'EU',
            'name'              => 'Turkey',
            'official_name'     => 'Republic of Turkey',
        ),
        'TT' => array(
            'alpha_2'           => 'TT',
            'alpha_3'           => 'TTO',
            'numeric'           => 780,
            'continent_alpha_2' => 'NA',
            'name'              => 'Trinidad and Tobago',
            'official_name'     => 'Republic of Trinidad and Tobago',
        ),
        'TV' => array(
            'alpha_2'           => 'TV',
            'alpha_3'           => 'TUV',
            'numeric'           => 798,
            'continent_alpha_2' => 'OC',
            'name'              => 'Tuvalu',
            'official_name'     => null,
        ),
        'TW' => array(
            'alpha_2'           => 'TW',
            'alpha_3'           => 'TWN',
            'numeric'           => 158,
            'continent_alpha_2' => 'AS',
            'name'              => 'Taiwan, Province of China',
            'official_name'     => 'Taiwan, Province of China',
        ),
        'TZ' => array(
            'alpha_2'           => 'TZ',
            'alpha_3'           => 'TZA',
            'numeric'           => 834,
            'continent_alpha_2' => 'AF',
            'name'              => 'Tanzania, United Republic of',
            'official_name'     => 'United Republic of Tanzania',
        ),
        'UA' => array(
            'alpha_2'           => 'UA',
            'alpha_3'           => 'UKR',
            'numeric'           => 804,
            'continent_alpha_2' => 'EU',
            'name'              => 'Ukraine',
            'official_name'     => null,
        ),
        'UG' => array(
            'alpha_2'           => 'UG',
            'alpha_3'           => 'UGA',
            'numeric'           => 800,
            'continent_alpha_2' => 'AF',
            'name'              => 'Uganda',
            'official_name'     => 'Republic of Uganda',
        ),
        'UM' => array(
            'alpha_2'           => 'UM',
            'alpha_3'           => 'UMI',
            'numeric'           => 581,
            'continent_alpha_2' => 'OC',
            'name'              => 'United States Minor Outlying Islands',
            'official_name'     => null,
        ),
        'US' => array(
            'alpha_2'           => 'US',
            'alpha_3'           => 'USA',
            'numeric'           => 840,
            'continent_alpha_2' => 'NA',
            'name'              => 'United States',
            'official_name'     => 'United States of America',
        ),
        'UY' => array(
            'alpha_2'           => 'UY',
            'alpha_3'           => 'URY',
            'numeric'           => 858,
            'continent_alpha_2' => 'SA',
            'name'              => 'Uruguay',
            'official_name'     => 'Eastern Republic of Uruguay',
        ),
        'UZ' => array(
            'alpha_2'           => 'UZ',
            'alpha_3'           => 'UZB',
            'numeric'           => 860,
            'continent_alpha_2' => 'AS',
            'name'              => 'Uzbekistan',
            'official_name'     => 'Republic of Uzbekistan',
        ),
        'VA' => array(
            'alpha_2'           => 'VA',
            'alpha_3'           => 'VAT',
            'numeric'           => 336,
            'continent_alpha_2' => 'EU',
            'name'              => 'Holy See (Vatican City State)',
            'official_name'     => null,
        ),
        'VC' => array(
            'alpha_2'           => 'VC',
            'alpha_3'           => 'VCT',
            'numeric'           => 670,
            'continent_alpha_2' => 'NA',
            'name'              => 'Saint Vincent and the Grenadines',
            'official_name'     => null,
        ),
        'VE' => array(
            'alpha_2'           => 'VE',
            'alpha_3'           => 'VEN',
            'numeric'           => 862,
            'continent_alpha_2' => 'SA',
            'name'              => 'Venezuela, Bolivarian Republic of',
            'official_name'     => 'Bolivarian Republic of Venezuela',
        ),
        'VG' => array(
            'alpha_2'           => 'VG',
            'alpha_3'           => 'VGB',
            'numeric'           => 92,
            'continent_alpha_2' => 'NA',
            'name'              => 'Virgin Islands, British',
            'official_name'     => 'British Virgin Islands',
        ),
        'VI' => array(
            'alpha_2'           => 'VI',
            'alpha_3'           => 'VIR',
            'numeric'           => 850,
            'continent_alpha_2' => 'NA',
            'name'              => 'Virgin Islands, U.S.',
            'official_name'     => 'Virgin Islands of the United States',
        ),
        'VN' => array(
            'alpha_2'           => 'VN',
            'alpha_3'           => 'VNM',
            'numeric'           => 704,
            'continent_alpha_2' => 'AS',
            'name'              => 'Viet Nam',
            'official_name'     => 'Socialist Republic of Viet Nam',
        ),
        'VU' => array(
            'alpha_2'           => 'VU',
            'alpha_3'           => 'VUT',
            'numeric'           => 548,
            'continent_alpha_2' => 'OC',
            'name'              => 'Vanuatu',
            'official_name'     => 'Republic of Vanuatu',
        ),
        'WF' => array(
            'alpha_2'           => 'WF',
            'alpha_3'           => 'WLF',
            'numeric'           => 876,
            'continent_alpha_2' => 'OC',
            'name'              => 'Wallis and Futuna',
            'official_name'     => null,
        ),
        'WS' => array(
            'alpha_2'           => 'WS',
            'alpha_3'           => 'WSM',
            'numeric'           => 882,
            'continent_alpha_2' => 'OC',
            'name'              => 'Samoa',
            'official_name'     => 'Independent State of Samoa',
        ),
        'YE' => array(
            'alpha_2'           => 'YE',
            'alpha_3'           => 'YEM',
            'numeric'           => 887,
            'continent_alpha_2' => 'AS',
            'name'              => 'Yemen',
            'official_name'     => 'Republic of Yemen',
        ),
        'YT' => array(
            'alpha_2'           => 'YT',
            'alpha_3'           => 'MYT',
            'numeric'           => 175,
            'continent_alpha_2' => 'AF',
            'name'              => 'Mayotte',
            'official_name'     => null,
        ),
        'ZA' => array(
            'alpha_2'           => 'ZA',
            'alpha_3'           => 'ZAF',
            'numeric'           => 710,
            'continent_alpha_2' => 'AF',
            'name'              => 'South Africa',
            'official_name'     => 'Republic of South Africa',
        ),
        'ZM' => array(
            'alpha_2'           => 'ZM',
            'alpha_3'           => 'ZMB',
            'numeric'           => 894,
            'continent_alpha_2' => 'AF',
            'name'              => 'Zambia',
            'official_name'     => 'Republic of Zambia',
        ),
        'ZW' => array(
            'alpha_2'           => 'ZW',
            'alpha_3'           => 'ZWE',
            'numeric'           => 716,
            'continent_alpha_2' => 'AF',
            'name'              => 'Zimbabwe',
            'official_name'     => 'Republic of Zimbabwe',
        ),
        'BQ' => array(
            'alpha_2'           => 'BQ',
            'alpha_3'           => 'BES',
            'numeric'           => 535,
            'continent_alpha_2' => 'SA',
            'name'              => 'Bonaire, Sint Eustatius and Saba',
            'official_name'     => 'Bonaire, Sint Eustatius and Saba',
        ),
        'CW' => array(
            'alpha_2'           => 'CW',
            'alpha_3'           => 'CUW',
            'numeric'           => 531,
            'continent_alpha_2' => 'SA',
            'name'              => 'Curaçao',
            'official_name'     => 'Curaçao',
        ),
        'SS' => array(
            'alpha_2'           => 'SS',
            'alpha_3'           => 'SSD',
            'numeric'           => 728,
            'continent_alpha_2' => 'AF',
            'name'              => 'South Sudan',
            'official_name'     => 'Republic of South Sudan',
        ),
        'SX' => array(
            'alpha_2'           => 'SX',
            'alpha_3'           => 'SXM',
            'numeric'           => 534,
            'continent_alpha_2' => 'NA',
            'name'              => 'Sint Maarten (Dutch part)',
            'official_name'     => 'Sint Maarten (Dutch part)',
        ),
    );

    /**
     * Get all countries.
     * 
     * @param string|null $continentCode The continent code
     * @return array
     */
    public function getAll($continentCode = null)
    {
        return $this->countries;
    }

    /**
     * Get all country names.
     * 
     * @param string|null $continentCode The continent code
     * @return array Retuns an array of aplha2 to name array.
     */
    public function getNames($continentCode = null)
    {
        $countries = array();

        foreach ($this->countries as $country) {
            $countries[$country['alpha_2']] = $country['name'];
        }

        return $countries;
    }

    /**
     * Find a country by alpha-2 code.
     * 
     * @param string $code Alpha-2 code
     * @return array|null
     */
    public function findByAlpha2($code)
    {
        if (isset($this->countries[$code])) {
            return $this->countries[$code];
        }

        return null;
    }

    /**
     * Find a country by alpha-3 code.
     * 
     * @param string $code Alpha-3 code
     * @return array|null
     */
    public function findByAlpha3($code)
    {
        foreach ($this->countries as $country) {
            if ($country->getAlpha3() === $code) {
                return $country;
            }
        }

        return null;
    }

    /**
     * Find a country by numeric code.
     * 
     * @param string $code Numeric code
     * @return array|null
     */
    public function findByNumeric($code)
    {
        foreach ($this->countries as $country) {
            if ($country->getNumeric() === $code) {
                return $country;
            }
        }

        return null;
    }
}